# build stage
#FROM node:lts-alpine as build-stage
#WORKDIR /app
#COPY package*.json ./
#RUN npm install
#COPY . .
#RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-c", "/usr/share/nginx/html/nginx.conf"]