# build stage
#FROM node:lts-alpine as build-stage
#WORKDIR /app
#COPY package*.json ./
#RUN npm install
#COPY . .
#RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY . /usr/share/nginx/html
COPY /cert/nginx.crt /etc/nginx/ssl/nginx.crt
COPY /cert/nginx.key /etc/nginx/ssl/nginx.key
EXPOSE 80 443
CMD ["nginx", "-c", "/usr/share/nginx/html/nginx.conf"]